
# Github Workflow that reacts on trigger to main branch, then builds the docker image and pushes it to Azure Container Registry
name: Build and Push Docker Image to ACR
on:
  push:
    branches:
      - main
jobs:
  build-and-push:
    permissions:
      id-token: write # Require write permission to Fetch an OIDC token.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure CLI Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          
      - name: Generate buildnumber based on date and time
        id: buildnumber
        run: echo "BUILD_NUMBER=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

      - name: Build and push Docker image
        run: |
          az acr login --name ${{ secrets.ACR_LOGIN_SERVER }}
          pwd
          ls -la
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/birthday-containerapp:${{ env.BUILD_NUMBER }} .
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/birthday-containerapp:${{ env.BUILD_NUMBER }}